# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settrump.ui'
#
# Created: Fri Feb 15 23:49:41 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(472, 203)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(472, 203))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Card1 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Card1.sizePolicy().hasHeightForWidth())
        self.Card1.setSizePolicy(sizePolicy)
        self.Card1.setMinimumSize(QtCore.QSize(86, 124))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/cards/c02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Card1.setIcon(icon)
        self.Card1.setIconSize(QtCore.QSize(81, 119))
        self.Card1.setObjectName(_fromUtf8("Card1"))
        self.horizontalLayout.addWidget(self.Card1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Card2 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Card2.sizePolicy().hasHeightForWidth())
        self.Card2.setSizePolicy(sizePolicy)
        self.Card2.setMinimumSize(QtCore.QSize(86, 124))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/cards/d02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Card2.setIcon(icon1)
        self.Card2.setIconSize(QtCore.QSize(81, 119))
        self.Card2.setObjectName(_fromUtf8("Card2"))
        self.horizontalLayout.addWidget(self.Card2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Card3 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Card3.sizePolicy().hasHeightForWidth())
        self.Card3.setSizePolicy(sizePolicy)
        self.Card3.setMinimumSize(QtCore.QSize(86, 124))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/cards/h02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Card3.setIcon(icon2)
        self.Card3.setIconSize(QtCore.QSize(81, 119))
        self.Card3.setObjectName(_fromUtf8("Card3"))
        self.horizontalLayout.addWidget(self.Card3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Card4 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Card4.sizePolicy().hasHeightForWidth())
        self.Card4.setSizePolicy(sizePolicy)
        self.Card4.setMinimumSize(QtCore.QSize(86, 124))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/cards/s02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Card4.setIcon(icon3)
        self.Card4.setIconSize(QtCore.QSize(81, 119))
        self.Card4.setObjectName(_fromUtf8("Card4"))
        self.horizontalLayout.addWidget(self.Card4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.joker = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joker.sizePolicy().hasHeightForWidth())
        self.joker.setSizePolicy(sizePolicy)
        self.joker.setMinimumSize(QtCore.QSize(86, 124))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/cards/joker.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.joker.setIcon(icon4)
        self.joker.setIconSize(QtCore.QSize(81, 119))
        self.joker.setObjectName(_fromUtf8("joker"))
        self.horizontalLayout.addWidget(self.joker)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.SecondHand = QtGui.QPushButton(Dialog)
        self.SecondHand.setObjectName(_fromUtf8("SecondHand"))
        self.horizontalLayout_2.addWidget(self.SecondHand)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Set Trump", None, QtGui.QApplication.UnicodeUTF8))
        self.SecondHand.setText(QtGui.QApplication.translate("Dialog", "Second Hand", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc